#!/usr/bin/env node
'use strict';

const experiments = require('./experiments');
const co = require('co');

function addDefaults() {
  co(function* () {
    yield experiments.addDefault();
  });
}

addDefaults();
